### ISSUE TITLE
Consider a change in the interface to better exploit dispatching in julia

### ISSUE THREAD

**Issue by jlperla** [EconForge/Dolo.jl#132]
Right now the "model" is simple a parsed YAML file.  It would be nicer to have this wrapped in a simple type (e.g. `Dolo.Model`) so that the interfaces can use multiple dispatch.  Beyond letting you add in future functionality to verify the model, do pre-processing, etc., it would also make it much for Julian to be able to dispatch on the type.

(Of course, I also think that you should ditch python entirely and rewrite `Dolo` as a DSL directly in Julia rather than as parsed YAML.... but that is another issue entirely!)

**Comment by albop** [comment]
Thanks for the suggestions @jlperla.
As for the model type the situation is a bit more complex that the one you describe. The model object is constructed by reading a yaml file, but each of its 
We do actually use mulitple dispatch for the interfaces: each imported model has its own singleton type.

**Comment by albop** [comment]
Thanks @jlperla ,
For the model, the situation is a bit more complex that the one you describe. The object that is used by all solution routines, has a known singleton type. Its fields also have a known type, at least in principle. Currently, the fields are constructed by reading the data from a yaml file (whose structure you can find in model.data), but one could also construct them in a different way. The singleton type is useful so that those of the solution routines which use the model functions can recompile these functions efficiently.
There are still some issues with type stability that we plan to tackle at some point, but I don't think they come from the model object or I misunderstood your question.

(Ditching python is not going to happen any time soon and the yaml approach has its own advantages. For instance, there should at some point a full linter (you can try now Dolo.lint(filename)) providing quick feedback about the model before you even start solving it.)
(But nothing prevents you or someone else to use a DSL or Julia directly to create a model object. The solution routines, should not have any dependency on YAML. They have a full Julia API.)

**Comment by albop** [comment]
To clarify one thing: by singleton type, I mean all models are a subtype of a `Model` object parameterized by a model-specific parameter. So when you import a file you get an object of class `Model{_id_of_your_model_}` and when you write function you can just specify `f(model:Model, ...) = ...` and the function will be compiled for your specific model when it is called for the first time.

**Comment by jlperla** [comment]
Oh sorry, I misunderstood something.  I thought that it was passing around the YAML directly because I couldn't get rid of the namespace when I was trying to modify your sample code.  But what I see now is that the real issue is that `Dolo.tabulate` should be exported and that it was dispatching perfectly reasonably.

**Comment by albop** [comment]
Cool! Btw, all feedbacks or suggestions on the internals are very appreciated!
