### ISSUE TITLE
Build MarkovChain type (or use QuantEcon's?) so we can use the !MarkovChain tag and import dtmscc

### ISSUE THREAD

**Issue by spencerlyon2** [EconForge/Dolo.jl#16]

**Comment by spencerlyon2** [comment]
I should note that we should implement the other types in https://github.com/EconForge/dolo/blob/master/dolo/compiler/objects.py also

**Comment by albop** [comment]
That would be useful.

Note that on objects we are still at a proof-of-concept phase and we need
to have a discussion about what we want to do for the long run.

Among the open questions:
- How do we construct the objects ? Do we simply construct them as we parse
the yaml file or do we have an intermediate layer as in dolo.py ? (In
dolo.py, there are intermediate objects, which retain the unevaluated
arguments, but perform some check when they are constructed. They are
currently constructed in dolo/compiler/language.py).
- Can we provide a kind of type inference mechanism so that we know in
advance the type of any node of the yaml tree and can check it against a
model prototype ? For instance, one could add type annotation to the
objects in objects.py and use them to check whether the unevaluated tree is
Ok.
- The contents of objects.py is merely a proof of concept. We need to make
an extensive list of what we need and for each object, decide which syntax
and which implementation we use (for instance, we're likely to use
quantecon and distributions whenever possible)

**Comment by spencerlyon2** [comment]
Ok glad to see you have some thoughts on this. It sounds like we should
discuss next week



// Spencer

On July 9, 2016 at 10:51:28 AM, Pablo Winant (notifications@github.com)
wrote:

That would be useful.

Note that on objects we are still at a proof-of-concept phase and we need
to have a discussion about what we want to do for the long run.

Among the open questions:
- How do we construct the objects ? Do we simply construct them as we parse
the yaml file or do we have an intermediate layer as in dolo.py ? (In
dolo.py, there are intermediate objects, which retain the unevaluated
arguments, but perform some check when they are constructed. They are
currently constructed in dolo/compiler/language.py).
- Can we provide a kind of type inference mechanism so that we know in
advance the type of any node of the yaml tree and can check it against a
model prototype ? For instance, one could add type annotation to the
objects in objects.py and use them to check whether the unevaluated tree is
Ok.
- The contents of objects.py is merely a proof of concept. We need to make
an extensive list of what we need and for each object, decide which syntax
and which implementation we use (for instance, we're likely to use
quantecon and distributions whenever possible)


On Fri, Jul 8, 2016 at 11:44 PM, Spencer Lyon <notifications@github.com>
wrote:

> I should note that we should implement the other types in
> https://github.com/EconForge/dolo/blob/master/dolo/compiler/objects.py
> also
>
> —
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly, view it on GitHub
> <https://github.com/EconForge/Dolo.jl/issues/16#issuecomment-231490157>,
> or mute the thread
> <
https://github.com/notifications/unsubscribe/AAQ5KQ3s0DVe-HtGs-hS7wSq1YGxBX4Tks5qTtLGgaJpZM4JIcya
>
> .
>

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub
<https://github.com/EconForge/Dolo.jl/issues/16#issuecomment-231526242>,
or mute
the thread
<https://github.com/notifications/unsubscribe/AA9J3MbPDgV3ML6zrmkKrUtDwLex1AJyks5qT28dgaJpZM4JIcya>
.
