### ISSUE TITLE
 Reverse order of endog and exog grids in decision rules

### ISSUE THREAD

**Issue by sglyon** [EconForge/Dolo.jl#47]
I would like to swap the order of endo and exo for the decision rules constructors and evaluators. 

The reason for this is that I can foresee some optimizations down the road. With Julia being column major, and our Cartesian product routines (`QuantEcon.gridmake`) supporting this layout when forming the product, we end up taking tensor products in _reverse_ order. Meaning, if we want to evaluate an interpolated function defined on a 2d input space we would compute basis matrices Phi_1 and Phi_2 (one for each dimension) and then do `row_kron(Phi_2, Phi_1)` to actually evaluate the tensor product.

The reason I want exog to come _last_ in the evaluation method is that I can often pre-compute all the necessary exogenous basis matrices (Phi_2 in the example) and then combine them with newly computed Phi_1 basis matrices when I need to evaluate the interpoland. I proposed we swap the order in the constructors too so that things are consistent.

I'm totally open for discussion on this -- I just wanted to put it up on my wishlist

**Comment by albop** [comment]
There are very good conventional reasons to keep (m,s) ordered in that
precise way :
- it is consistent with the literature and our model notations (you're not
suggesting f(X,S,M,x,s,m) are you ?)
- it matches the python side.
Now it looks to me the problem you mention is more related with the way we
evaluate everything in col-major, rather than the ordering of (m,s). More
specifically nothing prevents you from defining a function
'dr(m,s)=Phi(s)@Phi(m)', where you can precompute 'Phi(s)' although I would
tend to redefine @ so that it happens in the expected order.
On the other hand, if g is a cartesian grid for (m,s) where each line is a
value for m,s it is more annoying that g[:,1:size(s,1)] is not a grid for s
(similar thing happens for m).
So the overall filtering step for g is not done in a natural, ie is not
equivalent to filtering first w.r.t. s then w.r.t. m or the opposite.
Let's discuss (and keep things how they are for now).

**Comment by sglyon** [comment]
I actually think the main thing I need is not that the exogenous states come last, but that they are all grouped together. That way I can precompute the whole block of `s` and  `S` basis matrices together and then, as you say, just combine them with the new matrices for `m` and `M`.
