### ISSUE TITLE
set_calibration! printing

### ISSUE THREAD

**Issue by azheng25** [EconForge/Dolo.jl#98]
There is a bug when using set_calibration! for printing: MethodError: no method matching show(::IOContext{Base.AbstractIOBuffer{Array{UInt8,1}}}, ::DataStructures.OrderedDict{Symbol,Float64})

**Comment by sglyon** [comment]
This is just a bug for printing a calibration. 

It happens even without using the `set_calibration` function

**Comment by albop** [comment]
Any idea why this is happening ? Normally OrderedDict are printed just fine.

**Comment by sglyon** [comment]
No, I find it quite odd actually. 

The only definition of show in the file is [here](https://github.com/EconForge/Dolo.jl/blob/e4855e6ef0e2cbd1e19e39492274cd7c05c6f2b9/src/calibration.jl#L53) and nothing looks controversial to me there.

I think we can resolve the issue by defining a method

```julia
Base.show(io::IO, mc::ModelCalibration)
```

if someone wants to give it a shot

**Comment by albop** [comment]
It looks like there is something controversial with the line you mention since removing it makes everything work. 
The default representation of ModelCalibration objects is quite explicit (and works well in Atom), so I don't think it's not urgent to change it.
Actually, I'm ready to open an issue to niceify the representation of all Dolo objects, as soon as someone tells me the right way to implement the write/print/show family of functions.
